config/routes.rb
DevArcadenomadCom::Application.routes.draw do

  namespace :admin do
    root 'index#index'
    resources :categories
    resources :index
    resources :locations
  end

  resources :about

  match '/contact', to: 'about#new', via: 'get', as: 'contact_new'
  match '/contact', to: 'about#create', via: 'post', as: 'contact'

  resources :categories

  get '/locations/nearby/map(/:distance)' => 'locations#map', :defaults => { :distance => '20'}
  get '/locations/nearby(/:distance)' => 'locations#nearby', :defaults => { :distance => '20'}

  resources :locations do
    collection do
      get 'nearby'
    end
  end

  resources :games

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # Present the ArcadeNomad home page
  def index

    # Retrieve a random arcade
    @location = Location.where(['id >= ?', rand(Location.count) + 1]).first

    # Retrieve the most recently added arcades
    @locations = Location.order('created_at desc').limit(5)

    # Retrieve the most recently added barcades
    @barcades = Location.latest_by_type('Barcade')

    # Retrieve the most popular games according to appearance frequency
    @popular_games = Game.popular.limit(5)

    # Retrieve a random fact
    @factoid = Factoid.where(['id >= ?', rand(Factoid.count) + 1]).first

  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="row" style="margin: 10px;">
  <div class="col-md-8">

    <h1 style="color: #2c151f;">Break Out the Parachute Pants</h1>
    <p>
      ArcadeNomad is the web's most discerning retro arcade directory.
      Do you know where a 1980's arcade game is located? <%= link_to 'Submit it', new_location_path %> to the directory!
    </p>

    <h2>Arcade of the Minute - <%= link_to @location.name, location_path(@location.friendly_id) %></h2>

    <div id="welcome-map" data-latitude="<%= @location.latitude %>" data-longitude="<%= @location.longitude %>"></div>

    <div class="row">
      <div class="col-md-4">
        <h3>Latest Additions</h3>

        <ul class="list-group">

          <% @locations.each do |location| %>
              <li class="list-group-item">
                <h4 class="list-group-item-heading"><%= link_to location.name, location_path(location) %></h4>
                <span style="color:grey"><%= location.city %>, <%= location.state.abbreviation %></span>

              </li>
          <% end %>

        </ul>
        </div>

      <div class="col-md-4">
        <h3>Popular Games</h3>

        <% @popular_games.each do |pg| %>

            <li class="list-group-item"><h4 class="list-group-item-heading"><%= link_to pg.name, game_path(pg) %></h4>
              <span style="color:grey"><%= pg.game_count %> locations</span>
            </li>

        <% end %>

      </div>

      <div class="col-md-4">
        <h3>Random 1980's Fact</h3>

        <p>
          <%= @factoid.body %>
        </p>


      </div>

    </div>

    </div>

  <div class="col-md-4">

    <%= render :partial => 'shared/book'  %>

    <h3>Latest Barcades</h3>

    <ul class="list-group">

    <% @barcades.each do |barcade| %>

        <li class="list-group-item"><h4 class="list-group-item-heading"><%= link_to barcade.name, location_path(barcade) %></h4>
        <span style="color:grey"><%= barcade.city %>, <%= barcade.state.abbreviation %></span>
        </li>

    <% end %>
    </ul>

  </div>

</div>