config/routes.rb
DevArcadenomadCom::Application.routes.draw do

  namespace :admin do
    root 'index#index'
    resources :categories
    resources :index
    resources :locations
  end

  resources :about

  match '/contact', to: 'about#new', via: 'get', as: 'contact_new'
  match '/contact', to: 'about#create', via: 'post', as: 'contact'

  resources :categories

  get '/locations/nearby/map(/:distance)' => 'locations#map', :defaults => { :distance => '20'}
  get '/locations/nearby(/:distance)' => 'locations#nearby', :defaults => { :distance => '20'}

  resources :locations do
    collection do
      get 'nearby'
    end
  end

  resources :games

  root 'welcome#index'

end

app/controllers/about_controller.rb
#
#
#
#
#
class AboutController < ApplicationController

  #
  #
  #
  #
  def index
    @locations_count = Location.count
    @games_count = Game.count
  end

  #
  #
  #
  #
  def new

    @contact = ContactForm.new()

  end

  #
  #
  #
  #
  def create

    @contact = ContactForm.new(params[:contact_form])

    if @contact.deliver

      flash.now[:success] = 'Thank you for your message!'

    else

      flash.now[:error] = 'Could not send message.'
      render :new

    end

  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/create.html.erb
<div class="row" style="margin: 10px;">
  <div class="span-12 text-center">

<h1>Thank You</h1>

<p>

  Thank you for contacting us! We'll be in touch right after finishing this game of Asteroids...

</p>

      </div>
    </div>

app/views/about/index.html.erb
<div class="row" style="margin: 10px;">
  <div class="span-12">

<h1>About ArcadeNomad</h1>

<p>
  Growing up as a child of the 80's, I spent <i>a lot</i> of time playing arcade games. Whether at the mall, grocery store, or local truck stop,
  I was always begging my mother for a few quarters to pass the time. In the early days I recall playing Ms. Pac-man and Tron, while in the
  late 80's Rampage, Shinobi, Legend of Kage, and Double Dragon become familiar favorites.
</p>

<p>
  Over time the arcades slowly disappeared, and while consoles such as the Wii and PlayStation are undoubtedly a lot of fun, there's nothing quite
  like dropping a quarter into a classic cabinet. I created ArcadeNomad to help fellow retro gamers find their favorite games from the 80's, whether they are found in
  a Dave & Buster's restaurant or a dilapidated laundromat around the corner.
</p>

<h2>Download the Code</h2>

<p>
  Do you have an idea for a location-based directory but don't know where to begin? My book, "<a href="http://easyactiverecord.com">Easy Active Record for Rails Developers</a>",
  offers a comprehensive guide to building database-driven web applications such as ArcadeNomad using the powerful <a href="http://www.rubyonrails.org">Ruby on Rails</a> framework.
  Anybody who purchases the book is given a copy of <b>the latest ArcadeNomad.com code</b>!! You'll receive every single line of code used to run ArcadeNomad, in addition to
  detailed instructions explaining how to install the code on your laptop in order to learn how the pieces fit together.
</p>

<p>
  Keep in mind I would consider "<a href="http://easyactiverecord.com">Easy Active Record for Rails Developers</a>" to be an intermediate-level Rails book, meaning you
  should already have a general understanding of the Rails framework. If you're totally new to Rails, check out
  Michael Hartl's <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>. Otherwise, if you'd like to obtain a deep understanding of Rails' powerful
  Active Record ORM, this is the book for you! Check out the "<a href="http://easyactiverecord.com">Easy Active Record for Rails Developers</a>" for more details.
</p>

<h2>ArcadeNomad Statistics</h2>

ArcadeNomad currently tracks <%= link_to Location.count, locations_path %> arcades (the term "arcades" is loosely defined to mean any location hosting at least
one classic arcade game), and <%= Game.count %> arcade games. If you know the whereabouts of a classic arcade game that's not found in the ArcadeNomad
database, please create an account and <a href="">add the location</a> to the database!

</p>

      </div>
    </div>

app/views/about/new.html.erb
<div class="row" style="margin: 10px;">
  <div class="col-md-8">

    <h1>Contact ArcadeNomad</h1>

    <% if @contact.errors.any? %>
        <div>
          <h2><%= pluralize(@contact.errors.count, 'error') %> prohibited the e-mail from being sent:</h2>

          <ul>
            <% @contact.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      Have a comment, compliment or gripe? Would you like your favorite arcade added to the ArcadeNomad database? Let us know!
    </p>

    <%= form_for @contact, {url: contact_path, html: { role: 'form' }} do |f| %>

        <div class="form-group">
            <%= f.label :name, 'Your Name' %>
            <%= f.text_field :name, :class => 'form-control', :required => true %>
        </div>

        <div class="form-group">
            <%= f.label :name, 'Your E-mail Address' %>
            <%= f.text_field :email, :class => 'form-control', :required => true %>
        </div>

        <div class="form-group">
            <%= f.label :name, 'Your Message' %>
            <%= f.text_area :message, :class => 'form-control', :required => true %>
        </div>

        <div class="form-group">
          <%= f.submit 'Send message', :class=> 'btn btn-primary' %>
        </div>
    <% end %>

  </div>

  <div class="col-md-4">
    <%= render :partial => 'shared/book'  %>
  </div>

</div>