config/routes.rb
DevArcadenomadCom::Application.routes.draw do

  namespace :admin do
    root 'index#index'
    resources :categories
    resources :index
    resources :locations
  end

  resources :about

  match '/contact', to: 'about#new', via: 'get', as: 'contact_new'
  match '/contact', to: 'about#create', via: 'post', as: 'contact'

  resources :categories

  get '/locations/nearby/map(/:distance)' => 'locations#map', :defaults => { :distance => '20'}
  get '/locations/nearby(/:distance)' => 'locations#nearby', :defaults => { :distance => '20'}

  resources :locations do
    collection do
      get 'nearby'
    end
  end

  resources :games

  root 'welcome#index'

end

app/models/category.rb
#
#
#
#
class Category < ActiveRecord::Base

  #
  # Validations
  # 

  validates_presence_of :name

  #
  # Relations
  #

  has_many :locations, dependent: :restrict_with_error

  #
  # Plugins
  #

  extend FriendlyId
  friendly_id :name, :use => :slugged

end

app/controllers/admin/categories_controller.rb
#
#
#
#
#
class Admin::CategoriesController < ApplicationController

  # The user must authenticate before accessing this controller
  before_filter :authenticate

  # Set the controller layout to layouts/admin.html.erb
  layout 'admin'

  #
  #
  #
  def index
    @categories = Category.order('name asc')
  end

  def show
  end

  def new
  end

  def create
  end

  #
  #
  #
  def edit

    @category = Category.find(params[:id])

  end

  def update

    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:notice] = 'Category successfully updated.'
      redirect_to edit_admin_category_path(@category.id)
    else
      render 'edit'
    end

  end

  def destroy
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # Retrieve a list of categories having more than one assigned location.
  def index
    @categories = Category.where('locations_count > 0').order('name asc')
  end

  # Display a list of locations associated with a category.
  def show
    @category = Category.friendly.find(params[:id])
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="row" style="margin: 10px;">
  <div class="col-md-8">

    <h1>Categories</h1>

    <% if @categories.length > 0 %>

      <ul class="list-group">

        <% @categories.each do |category| %>
          <li class="list-group-item">
            <h4 class="list-group-item-heading"><%= link_to category.name, category_path(category.friendly_id) %></h4>
            <span style="color:grey"><%= category.locations.count %> locations</span>
          </li>
        <% end %>

      </ul>

    <% else %>
        <p>No categories available.</p>
    <% end %>

  </div>

  <div class="col-md-4">

    <%= render :partial => 'shared/book'  %>

  </div>

</div>

app/views/categories/show.html.erb
<div class="row" style="margin: 10px;">
  <div class="col-md-8">

    <h1><%= @category.name %></h1>

    <% if @category.locations.size > 0 %>
        <ul class="list-group">
          <% @category.locations.each do |location| %>
              <li class="list-group-item">
                <h4 class="list-group-item-heading"><%= link_to location.name, location_path(location.friendly_id) %></h4>
                <span style="color:grey"><%= location.description %></span>
              </li>
          <% end %>
        </ul>
    <% else %>
        <p>No category locations available.</p>
    <% end %>

    <p>
      Category last updated: <%= localize(@category.created_at, :format => :last_updated) %>
    </p>

  </div>

  <div class="col-md-4">

    <%= render :partial => 'shared/book'  %>

  </div>

</div>