config/routes.rb
DevArcadenomadCom::Application.routes.draw do

  namespace :admin do
    root 'index#index'
    resources :categories
    resources :index
    resources :locations
  end

  resources :about

  match '/contact', to: 'about#new', via: 'get', as: 'contact_new'
  match '/contact', to: 'about#create', via: 'post', as: 'contact'

  resources :categories

  get '/locations/nearby/map(/:distance)' => 'locations#map', :defaults => { :distance => '20'}
  get '/locations/nearby(/:distance)' => 'locations#nearby', :defaults => { :distance => '20'}

  resources :locations do
    collection do
      get 'nearby'
    end
  end

  resources :games

  root 'welcome#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ArcadeNomad</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <%= include_gon %>
  <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans:400,800' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= csrf_meta_tags %>
</head>

<body>

<div>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="border-bottom: 2px solid black;">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/admin">ArcadeNomad&nbsp;<%= image_tag('arcadenomad-logo.png', :id => 'logo') %></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li><%= link_to 'Arcades', admin_locations_path %></li>
          <li><%= link_to 'Games', games_path %></li>
          <li><%= link_to 'Categories', admin_categories_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->

    </div><!-- /.container-fluid -->
  </nav>

  <div class="container" style="padding-left: 0px; padding-right: 0px;">

    <div class="row">
      <div class="col-md-12">
        <% flash.each do |key, value| %>
            <div class="<%= flash_class(key) %>">
              <%= value %>
            </div>
        <% end %>
      </div>
    </div>

    <%= yield %>

  </div>

</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>ArcadeNomad</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <%= include_gon %>
  <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans:400,800' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= csrf_meta_tags %>
</head>

<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="border-bottom: 2px solid black;">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ArcadeNomad&nbsp;<%= image_tag('arcadenomad-logo.png', :id => 'logo') %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_url %></li>
        <li><%= link_to 'Arcades', locations_path %></li>
        <li><%= link_to 'Games', games_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
        <li><%= link_to 'What\'s Nearby', nearby_locations_path %></li>
        <li><%= link_to 'About ArcadeNomad', about_index_path %></li>
        <li><%= link_to 'Get in Touch', contact_new_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

  <div class="container" style="padding-left: 0px; padding-right: 0px;">

    <div class="row">
      <div class="col-md-12">
      <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %>">
            <%= value %>
          </div>
      <% end %>
      </div>
    </div>

    <%= yield %>

  </div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      Copyright &copy; 2014 <a href="http://www.wjgilmore.com">W.J. Gilmore, LLC</a>. All trademarks mentioned on this website are the property of their respective owners.
    </div>
  </div>
</div>

<!--
<div id="footer" class="visible-xs">
    <div class="col-xs-12 navbar-inverse navbar-fixed-bottom" style="background-color: #2c151f;">
      <div class="row" id="bottomNav">
        <div class="col-xs-4 text-center"><a href="/locations/"><i class="glyphicon glyphicon-star"></i> <br>Arcades</a></div>
        <div class="col-xs-4 text-center"><a href="/games"><i class="glyphicon glyphicon-star"></i> <br>Games</a></div>
        <div class="col-xs-4 text-center"><a href="/locations/nearby"><i class="glyphicon glyphicon-globe"></i> <br>Nearby</a></div>
      </div>
    </div>
</div>
-->

<%= render :partial => 'shared/ga' if Rails.env.production? %>
</body>
</html>